[all_vms]
vm-001 ansible_host=10.10.101.210 ansible_user=ubuntu
vm-002 ansible_host=10.10.101.211 ansible_user=ubuntu

[all_vms:vars]
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'